### ISSUE TITLE
How to write `entry function` when using `netlifter` to test other protocol programs?

### ISSUE THREAD

**Issue by lijunqiang123** [qingkaishi/netlifter#1]
Hello, I am very interested in your excellent work. If I want to use `netlifter` to test other protocol programs, do I need to write entry functions for each protocol program? For example, the command to test `smp` is: `./popeye benchmarks/smp.bc -popeye-entry=popeye_main_smp -popeye-output=dot:smp.dot -popeye-output=bnf`. Function `popeye_main_smp` is not in the original code. I am looking forward to your reply!

**Comment by qingkaishi** [comment]
Hi, thanks for your question. You can refer to the readme or the Bitcode (.bc) file for details. I believe this info has been included in the readme.

**Comment by lijunqiang123** [comment]
> Hi, thanks for your question. You can refer to the readme or the Bitcode (.bc) file for details. I believe this info has been included in the readme.

Thank you for your reply. I have read this [document (https://docs.google.com/document/d/1u80FbynWhiit1cgC0s5sGQcInXIbXNDOs3kEJbGR9VA/edit#heading=h.5fzdf7my25s5). 
I don't know if the following stub code is written in the original program code. If yes, how can I compile the original program code? Which header file should I include so that I can compile the original program code?
![image](https://github.com/qingkaishi/netlifter/assets/22146584/124ed7d1-ccff-4d75-93ca-5be86295315a)

**Comment by qingkaishi** [comment]
issues not related to the project.
