### ISSUE TITLE
Inquiry Regarding popeye Tool Input and Compilation Process

### ISSUE THREAD

**Issue by FlYwithcoder** [qingkaishi/netlifter#2]
Hello Qingkai Shi,
I hope this message finds you well. I have been exploring the popeye tool as detailed in your paper and I'm particularly interested in the procedure described for analyzing protocol parsers. I noticed in your GitHub repository, under the bencharks/popeye directory, there's a readme.txt file which I assume contains relevant information.
Could you kindly confirm if the readme.txt located in the benchmarks/popeye directory outlines the exact input expected by the popeye tool for protocol analysis as per the methodology discussed in the paper? Additionally, I would like to understand if using Clang-12 and WLLVM is the recommended way to compile the protocol parsers before analysis with Popeye.
If there are specific instructions or prerequisites for the compilation and analysis process using Clang-12 and WLLVM, could you please elaborate on them or point me to the appropriate resource?
Thank you for your time and effort, and I appreciate the work you've done with the popeye tool. It is indeed a fascinating project.
Looking forward to your guidance.
Best regards,
Fei Hao.

**Comment by qingkaishi** [comment]
You are right. Please also refer to the readme file in the root directory. 

wllvm and clang-12 are good tools to generate the bitcode. I used them, too.

**Comment by FlYwithcoder** [comment]
> You are right. Please also refer to the readme file in the root directory.
> 
> wllvm and clang-12 are good tools to generate the bitcode. I used them, too.

Thank you very much for your prompt and helpful reply! I really appreciate the time and effort you took to address my question.
