### ISSUE TITLE
Build Failure Due to Missing Libraries in 'popeye' Project

### ISSUE THREAD

**Issue by FlYwithcoder** [qingkaishi/netlifter#3]
Hello,
I've encountered a difficult problem while attempting to build the 'popeye' project according to the guidelines specified in the project's [documentation.](https://docs.google.com/document/d/1u80FbynWhiit1cgC0s5sGQcInXIbXNDOs3kEJbGR9VA/edit#heading=h.5fzdf7my25s5) During the build process, I received an error indicating that several specific libraries could not be found: libPPYCore, libPPYMemory, libPPYTransform, libPPYBNF, and libPPYSupport.
Here is the detailed error message that I came across ![err1](https://github.com/qingkaishi/netlifter/assets/64963018/5c615d89-0175-4ad2-925a-9dcd66a726b6).
To aid in diagnosing and resolving this issue, I am providing the relevant contents of my CMakeLists.txt file 
![2](https://github.com/qingkaishi/netlifter/assets/64963018/b0a1622a-6dbd-4c16-a67d-a54ceeb9e0c1)
I have attempted to look up the documentation and search for possible locations of these libraries, but I have not found any clues about them. I am unsure whether these library files should be compiled by myself or if they should be obtained from somewhere, or if my build process is missing some steps.
I would appreciate any advice on how to handle this problem or guidance on the correct steps to find and link these libraries.
Thank you very much for your help and support, I am looking forward to your reply!
Best regards!

**Comment by qingkaishi** [comment]
Basically, I think you should learn how to use CMake first. You cannot directly run `make` in `netlifter/tools/...`

1. Goto ~/RE/netlifter
2. Create a directory `build`
3. Goto ~/RE/netlifter/build
4. Run `cmake .. && make`

BTW, can you disclose your name and affiliation before follow-up discussions? I think this will help our discussion.
